/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 scene.gltf --transform
Author: BarracudaByte (https://sketchfab.com/barracudabyte)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/stylized-coin-8cd6f95c44994ed5944a42892d0ffc10
Title: Stylized Coin
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("./Assets/coin/scene-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Coin_Material_0.geometry}
        material={materials.Material}
      />
    </group>
  );
}

useGLTF.preload("./Assets/coin/scene-transformed.glb");
