/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 roboting.gltf
Author: shertiku (https://sketchfab.com/shertiku)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/melee-robot-t-pose-brawl-stars-eeef52769a084d44bade1aa48b084a10
Title: Melee Robot t-pose Brawl Stars
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/scene.gltf");
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={24.317}>
          <primitive object={nodes._rootJoint} />
          <skinnedMesh
            geometry={nodes.Object_100.geometry}
            material={materials.Material}
            skeleton={nodes.Object_100.skeleton}
          />
          <skinnedMesh
            geometry={nodes.Object_102.geometry}
            material={materials.Material}
            skeleton={nodes.Object_102.skeleton}
          />
          <skinnedMesh
            geometry={nodes.Object_104.geometry}
            material={materials.Material}
            skeleton={nodes.Object_104.skeleton}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/scene.gltf");
